#!/usr/bin/env php
<?php

$basePath = dirname(__DIR__);

require_once $basePath . '/vendor/autoload.php';

$app = require_once $basePath . '/bootstrap/app.php';

$kernel = $app->make('Illuminate\\Console\\Kernel');

exit($kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
));
